name: CI

on:
  push:
    branches: [ main ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create a Config.json
        run: |
            touch key.json
            echo $GOOGLEKEY > key.json
            cat key.json
            touch config.json
            echo $CONFIG > config.json
        shell: bash
        env:
          GOOGLEKEY: ${{secrets.GOOGLE_SERVICE_CONECTION}}
          CONFIG: ${{ secrets.CONFIG_BOT }}
        
      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key:  ${{ secrets.HEROKU_APIKEY }}
          dockerfile_directory: ./
          process_type: botcalendar
