name: "Pull Request Validate"

on: pull_request

jobs:
  validations:
    name: "Validations"
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          max-line-length: "150"
      
      - run: |
          cp config.json.example config.json
          cp key.json.example key.json

      - name: Security check - Bandit
        uses: ./
        with:
          ignore_failure: true
